### PR TITLE
Allow users to yield a simple String to be rendered

### PR DESCRIPTION
**Pull request by r7kamura**
Added a missing feature from ActionView::Helpers::CaptureHelper
- http://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-content_for
- https://github.com/rails/rails/blob/fcbd2e821e12fdf66ad2f28e97992a7cd75f529e/actionview/lib/action_view/helpers/capture_helper.rb#L149-L162

### CODE REVIEW

**Comment by zzak** [comment]
@r7kamura Willing to rebase this?

Thanks

**Comment by r7kamura** [comment]
@zzak Oh, I haven't noticed the conflict! I just rebased it, thanks 🙏

**Comment by zzak** [comment]
@r7kamura どうも！

**Comment by kirqe** [comment]
I'm getting 

`undefined method yield_content for #<Web:...> Did you mean? yield_self`

using
```
- content_for :title, "SOME TITLE"
= yield_content :title
```

**Pull request merged**
