### PR TITLE
Enforce ruby guidelines using rubocop and migrate specs to new format

### PR DESCRIPTION
**Pull request by stjhimy**
Rubocop detected ~1300 offenses and it was able to `--auto-correct` around 1100. I fixed the remaining 200 manually.
I also excluded a few cops using the `.rubocop.yml`, those are mostly cops that requires heavy method extraction or huge changes in order to fix the offenses.
[Transpec](https://github.com/yujinakayama/transpec) was used to migrate all the specs to the newest format.  

```
Inspecting 41 files
.........................................
```

### CODE REVIEW

**Comment by rennex** [comment]
There's a check for whether the Ruby version is > 1.9.0, so presumably Sinatra still supports 1.8.7? Can't go changing `:foo =>` style hashes into `foo:` in that case.

Additionally, I think most of the changes I'm seeing aren't fixes I'd agree with personally; they're just style collisions which are a matter of taste. For example, changing double-quoted strings into single-quoted ones, replacing `and` with `&&` and `or` with `||`, adding parentheses, removing the non-standard but useful vertical alignment of blocks of code, etc. Don't fix it if it ain't broken?

**Comment by stjhimy** [comment]
Yes, this is why the title is "Enforce ruby guidelines using rubocop"
https://github.com/bbatsov/ruby-style-guide

**Comment by stjhimy** [comment]
About ruby 1.8.7 it was dropped from the `.travis.yml` so we still supporting it @zzak ?

**Comment by TrevorBramble** [comment]
@stjhimy That's correct. Ruby 2.2.0 is the lowest supported version going forward.

**Comment by rennex** [comment]
The style guide doesn't say single quotes are better than double quotes, just that usage should be consistent. Looks like the existing preference is double quotes.

Also what's with those spec changes? Is `x.should == 42` really worse than "expect x to be 42" with parentheses, dots, and underscored added in seemingly random gaps? ;)

**Comment by stjhimy** [comment]
http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/

```
The problem is that rspec-expectations defines should on Kernel, and BasicObject does not include Kernel…so instance.should triggers method_missing and gets delegated to the target object. The result is actually :some_object.should be_fuzzy which is clearly false (or rather, a NoMethodError).

It gets even more confusing when using delegate in the standard library. It selectively includes some of Kernel's methods…which means that if rspec-expectations gets loaded before delegate, should will work properly on delegate objects, but if delegate is loaded first, it will proxy the should calls just like in our FuzzyProxy example above.

The underlying problem is RSpec's should syntax: for should to work properly, it must be defined on every object in the system… but RSpec does not own every object in the system and cannot ensure that it always works consistently. As we've seen, it doesn't work as RSpec expects on proxy objects. Note that this isn't just a problem with RSpec; it's a problem with minitest/spec's must_xxx syntax as well.
```

**Comment by Freaky** [comment]
This smells like two pull requests squished into one.

Maybe split it into one to make rubocop happy and one to make rspec happy?  Then they can be reviewed and tested independently.

**Comment by zzak** [comment]
I don't want to merge this type of patch in, it's too big and hard to justify the value of these changes.

These changes are mostly superficial and for me having the ability to git blame and bisect without dealing with this patch is more valuable.

Thank you for understanding!

**Comment by stjhimy** [comment]
@zzak @rennex I understand your point.
Migrating to the newest rspec syntax also allow us to move forward to the latest gem version.

@Freaky Got it.

I will close the pull request for now, if we decide to move to the latest rspec then we can migrate the specs I guess. 

Thanks everyone.

**Comment by zzak** [comment]
Agree, we should update rspec, but that is a separate issue to style guidelines.

Thanks <3

**Pull request closed without merging**
