### PR TITLE
Add missing specs for filters/helpers when using regex namespace

### LINKED ISSUE #176: 'helpers' and 'before' not available for namespace with regex
I have a namespace with regex:

```
namespace /provider\/([^\/&?]+)\/tag\/([^\/&?]+)/ do
```

I attempted to add some helpers (tried both module and block syntax), and also a ```before``` block. The ```before``` block does not execute, and the helper methods are not available.

simply replacing the above regex with params syntax:

```
namespace '/provider/:provider/tag/:provider_id' do
```

causes the ```before``` block to be executed and the helper methods to be available within routes.

Of course, this is a very simplistic regex, provided as an example. I have more complex regex that can't be replaced by params syntax.

### PR DESCRIPTION
**Pull request by stjhimy**
Close #176

### CODE REVIEW

**Comment by zzak** [comment]
Do we actually support namespace with regex?

**Comment by stjhimy** [comment]
Yes @zzak 
https://github.com/sinatra/sinatra-contrib/blob/master/lib/sinatra/namespace.rb#L281

This pull request just add missing specs for filters/helpers under a regex namespace.

**Comment by zzak** [comment]
Ah yeah, I see. However, I'm not so sure the current state of namespace since sinatra master broke the specs. /cc #200

**Comment by stjhimy** [comment]
#200 is fixed using `sinatra=master`
This is ready to merge.

**Comment by stjhimy** [comment]
Conflicts fixed.
Sorry @zzak #200 still an issue on master, I will work to fix this week and rebase here.

**Pull request merged**
