### PR TITLE
Fix namespace extension to support latest Sinatra version

### PR DESCRIPTION
**Pull request by 304**
This fix should resolve some of the issues with namespace extension.

I haven't worked with this extension before, so I was completely relying on tests during my investigation. Please feel free to comment.

Issue: https://github.com/sinatra/sinatra-contrib/issues/200

### CODE REVIEW

**Comment by stjhimy** [comment]
Amazing! 
You must require `mustermann` somewhere in order to pass all the checks, that's because it is required only on sinatra/master.

See the errors on travis:
https://travis-ci.org/sinatra/sinatra-contrib/builds/145003731

**Comment by 304** [comment]
Thanks @stjhimy! The `mustermann` error is gone. 
However, there is still an issue with `splat`. And looks like it is caused by `sinatra`.

```
sinatra=stable bundle exec rake

> 845 examples, 7 failures, 14 pending
```

But the latest version of `sinatra` contains a fix for it.

```
sinatra=master bundle exec rake

> 845 examples, 0 failures, 14 pending
```

What do you think is the best way for resolve it?

**Comment by zzak** [comment]
zdfnaksdjfasjdf;laskdjfpoiasdjfasdf

THANK YOU!!!

I can't believe the fix was this easy, and have been pining over this for literally weeks.

**Comment by zzak** [comment]
@304 @stjhimy Ahh, yeah there is an issue when using regular expression in the path.

If we don't skip `spec/namespace_spec.rb:82 and :101`, I get the following failures still:

```
Failures:

  1) Sinatra::Namespace HTTP GET when namespace is a named parameter accepts the path as regular expression
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:86:in `block (5 levels) in <top (required)>'

  2) Sinatra::Namespace HTTP GET when namespace is a regular expression accepts the path as a named parameter
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:105:in `block (5 levels) in <top (required)>'

  3) Sinatra::Namespace HTTP HEAD when namespace is a named parameter accepts the path as regular expression
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:86:in `block (5 levels) in <top (required)>'

  4) Sinatra::Namespace HTTP HEAD when namespace is a regular expression accepts the path as a named parameter
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:105:in `block (5 levels) in <top (required)>'

  5) Sinatra::Namespace HTTP POST when namespace is a named parameter accepts the path as regular expression
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:86:in `block (5 levels) in <top (required)>'

  6) Sinatra::Namespace HTTP POST when namespace is a regular expression accepts the path as a named parameter
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:105:in `block (5 levels) in <top (required)>'

  7) Sinatra::Namespace HTTP PUT when namespace is a named parameter accepts the path as regular expression
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:86:in `block (5 levels) in <top (required)>'

  8) Sinatra::Namespace HTTP PUT when namespace is a regular expression accepts the path as a named parameter
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:105:in `block (5 levels) in <top (required)>'

  9) Sinatra::Namespace HTTP DELETE when namespace is a named parameter accepts the path as regular expression
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:86:in `block (5 levels) in <top (required)>'

  10) Sinatra::Namespace HTTP DELETE when namespace is a regular expression accepts the path as a named parameter
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:105:in `block (5 levels) in <top (required)>'

  11) Sinatra::Namespace HTTP OPTIONS when namespace is a named parameter accepts the path as regular expression
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:86:in `block (5 levels) in <top (required)>'

  12) Sinatra::Namespace HTTP OPTIONS when namespace is a regular expression accepts the path as a named parameter
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:105:in `block (5 levels) in <top (required)>'

  13) Sinatra::Namespace HTTP PATCH when namespace is a named parameter accepts the path as regular expression
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:86:in `block (5 levels) in <top (required)>'

  14) Sinatra::Namespace HTTP PATCH when namespace is a regular expression accepts the path as a named parameter
     Failure/Error: send(verb, '/foo/bar').should be_ok
       expected ok? to return true, got false
     # ./spec/namespace_spec.rb:105:in `block (5 levels) in <top (required)>'

Finished in 2.6 seconds   
845 examples, 14 failures

Failed examples:

rspec ./spec/namespace_spec.rb:82 # Sinatra::Namespace HTTP GET when namespace is a named parameter accepts the path as regular expression
rspec ./spec/namespace_spec.rb:101 # Sinatra::Namespace HTTP GET when namespace is a regular expression accepts the path as a named parameter
rspec ./spec/namespace_spec.rb:82 # Sinatra::Namespace HTTP HEAD when namespace is a named parameter accepts the path as regular expression
rspec ./spec/namespace_spec.rb:101 # Sinatra::Namespace HTTP HEAD when namespace is a regular expression accepts the path as a named parameter
rspec ./spec/namespace_spec.rb:82 # Sinatra::Namespace HTTP POST when namespace is a named parameter accepts the path as regular expression
rspec ./spec/namespace_spec.rb:101 # Sinatra::Namespace HTTP POST when namespace is a regular expression accepts the path as a named parameter
rspec ./spec/namespace_spec.rb:82 # Sinatra::Namespace HTTP PUT when namespace is a named parameter accepts the path as regular expression
rspec ./spec/namespace_spec.rb:101 # Sinatra::Namespace HTTP PUT when namespace is a regular expression accepts the path as a named parameter
rspec ./spec/namespace_spec.rb:82 # Sinatra::Namespace HTTP DELETE when namespace is a named parameter accepts the path as regular expression
rspec ./spec/namespace_spec.rb:101 # Sinatra::Namespace HTTP DELETE when namespace is a regular expression accepts the path as a named parameter
rspec ./spec/namespace_spec.rb:82 # Sinatra::Namespace HTTP OPTIONS when namespace is a named parameter accepts the path as regular expression
rspec ./spec/namespace_spec.rb:101 # Sinatra::Namespace HTTP OPTIONS when namespace is a regular expression accepts the path as a named parameter
rspec ./spec/namespace_spec.rb:82 # Sinatra::Namespace HTTP PATCH when namespace is a named parameter accepts the path as regular expression
rspec ./spec/namespace_spec.rb:101 # Sinatra::Namespace HTTP PATCH when namespace is a regular expression accepts the path as a named parameter
```

**Comment by stjhimy** [comment]
@zzak yes, this is the one we must patch `mustermann` and add support for `/:foo/ + %r{/bar}` in order to work.

**Comment by zzak** [comment]
@stjhimy That is no longer an issue, when we use the `master` branch on mustermann (until the patch is released).

The remaining blockers are described in 2d2a445

**Pull request merged**
